### ISSUE TITLE
Does not compile with Kernel 4.8

### ISSUE THREAD

**Issue by freswa** [dorimanx/exfat-nofuse#91]
Distribution: Arch
Build via DKMS

```
/var/lib/dkms/exfat/162.051167c/build/exfat_super.c:352:15: error: too few arguments to function ‘full_name_hash’
qstr->hash = full_name_hash(qstr->name, exfat_striptail_len(qstr));
/var/lib/dkms/exfat/162.051167c/build/exfat_super.c:455:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
.d_compare = exfat_cmpi,
```

**Comment by lgrootnoob** [comment]
Duplicate, also arch

**Comment by nettucu** [comment]
Duplicate, also arch
