### ISSUE TITLE
Does not compile with 3.11-rc2

### ISSUE THREAD

**Issue by escalade** [dorimanx/exfat-nofuse#7]
CC [M]  exfat_super.o
exfat_super.c:365:2: error: unknown field ‘readdir’ specified in initializer
  .readdir    = exfat_readdir,
  ^
exfat_super.c:365:2: warning: initialization from incompatible pointer type [enabled by default]
exfat_super.c:365:2: warning: (near initialization for ‘exfat_dir_operations.write’) [enabled by default]
make[2]: **\* [exfat_super.o] Error 1
make[1]: **\* [_module_] Error 2
make[1]: Leaving directory `/usr/src/linux-3.11.0-1-ARCH'
make: **\* [all] Error 2
