### PR TITLE
exfat_super.c: Support kernel 4.8

### LINKED ISSUE #91: Does not compile with Kernel 4.8
Distribution: Arch
Build via DKMS

```
/var/lib/dkms/exfat/162.051167c/build/exfat_super.c:352:15: error: too few arguments to function ‘full_name_hash’
qstr->hash = full_name_hash(qstr->name, exfat_striptail_len(qstr));
/var/lib/dkms/exfat/162.051167c/build/exfat_super.c:455:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
.d_compare = exfat_cmpi,
```

### PR DESCRIPTION
**Pull request by evan-a-a**
Changes introduced by commits 8387ff2577e and 6fa67e707 in the kernel
prompted this change.

Fixes #91 and #89

### CODE REVIEW

**Comment by evan-a-a** [comment]
The Arch AUR package is already using my fork while the PR is still open.

**Comment by lgrootnoob** [comment]
Decent, I was using it as a built in kernel driver. Didnt even bother to
notice the arch package oops

**Comment by libcg** [comment]
:+1:

**Comment by dorimanx** [comment]
Sorry for delay, didnt noticed. was away from githug for some time.
Thanks for support people! :)
