### ISSUE TITLE
Fails to build with 4.16-rc1

### ISSUE THREAD

**Issue by escalade** [dorimanx/exfat-nofuse#126]
Getting errors like this:

``
exfat_super.c: In function 'exfat_create':
exfat_super.c:750:16: error: wrong type argument to increment
  dir->i_version++;
``

**Comment by terraluna977** [comment]
Check my fix in "Pull-requests"
